# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nco8Was_5XicIYffDfOUKV8R7D10FisU
"""

import mod as ela
print(ela.preturn())

